### ISSUE TITLE
Computation time

### ISSUE THREAD

**Issue by amifsud** [loco-3d/sensing#1]
Computation time optimization for the estimator is needed to use it in a control loop at 1ms.

**Comment by amifsud** [comment]
Three ways of optimization:

- Using stack-of-tasks V3

- Using Pinocchio for analytical derivatives

- Code re-factoring and using eigen more efficiently

**Comment by andreadelprete** [comment]
We did some measurements and found out that about half of the computation time of the flexibility observer is taken by sot-dynamics, which computes the input signals of the observer. This means that when we'll shift to the new version of sot-dynamics (sot v3), which is based on pinocchio, this time will be automatically reduced!
