### ISSUE TITLE
Identify HRP-2's ankle spring stiffness and damping

### ISSUE THREAD

**Issue by andreadelprete** [loco-3d/sensing#3]
The flexibility observer uses a linear model for the springs and dampers in HRP-2's feet. Currently the stiffness and damping parameters have been (partially) tuned by hand, using a viewer to check whether the resulting estimation was realistic. A better way to tackle the problem would be to use a motion-capture system as ground truth for the base estimation, and then tune stiffness and damping to minimize the estimation error.

**Comment by andreadelprete** [comment]
@thomasfla is taking care of this issue

**Comment by thomasfla** [comment]
Stiffness has been identified using mo-cap. Damping part have since been considered neglectable as we couldn't see the effect on the recorded data.
